version: "3"

services:
  webserver:
    container_name: webserver
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./docker/webserver:/etc/nginx/conf.d
    ports:
      - 8000:80

  app:
    container_name: app
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/app
    working_dir: /app

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root

networks:
  default:
